name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Create analysis_options.yaml file with the specified rules
      - name: Create analysis_options.yaml
        run: |
          echo "include: package:flutter_lints/flutter.yaml" > analysis_options.yaml
          echo "" >> analysis_options.yaml
          echo "linter:" >> analysis_options.yaml
          echo "  rules:" >> analysis_options.yaml
          echo "    unused_field: false" >> analysis_options.yaml
          echo "    undefined_function: false" >> analysis_options.yaml
          echo "    not_initialized_non_nullable_instance_field: false" >> analysis_options.yaml

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
